/**
 * Writes `src/app/icon.svg` from `mark-geometry` so favicon paths cannot drift
 * from the React mark. Favicons cannot use CSS variables — hexes match
 * `--ms-accent` / gruvbox fg in `styles/globals.css` and the TUI mockup.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  markHandle,
  markLens,
  markPulse,
  markViewBox,
} from '../src/components/mongoscope-mark/mark-geometry'

const faviconColors = {
  lightFg: '#3c3836',
  lightAccent: '#427b58',
  darkFg: '#ebdbb2',
  darkAccent: '#8ec07c',
} as const

function buildFaviconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${markViewBox}" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by scripts/generate-icon.ts from mark-geometry. Do not edit by hand. -->
  <style>
    @media (prefers-color-scheme: dark) {
      .fg { stroke: ${faviconColors.darkFg}; }
      .ac { stroke: ${faviconColors.darkAccent}; }
    }
  </style>
  <circle class="fg" cx="${markLens.cx}" cy="${markLens.cy}" r="${markLens.r}" stroke="${faviconColors.lightFg}" stroke-width="${markLens.strokeWidth}"/>
  <path class="fg" d="${markHandle.d}" stroke="${faviconColors.lightFg}" stroke-width="${markHandle.strokeWidth}"/>
  <path class="ac" d="${markPulse.d}" stroke="${faviconColors.lightAccent}" stroke-width="${markPulse.strokeWidth}"/>
</svg>
`
}

const docsRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const outPath = join(docsRoot, 'src/app/icon.svg')

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, buildFaviconSvg())
console.log(`wrote ${outPath}`)
